import { ChatSession, ChatMessage } from '@/hooks/useAIChat';

/**
 * 将聊天会话转换为Markdown格式
 */
export function sessionToMarkdown(session: ChatSession): string {
  const lines: string[] = [];
  
  // 标题
  lines.push(`# ${session.title}`);
  lines.push('');
  
  // 元数据
  lines.push(`**创建时间**: ${session.createdAt.toLocaleString('zh-CN')}`);
  lines.push(`**更新时间**: ${session.updatedAt.toLocaleString('zh-CN')}`);
  if (session.category) {
    lines.push(`**分类**: ${session.category}`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');
  
  // 消息内容
  session.messages.forEach((message, index) => {
    if (message.role === 'user') {
      lines.push(`## 💬 问题 ${Math.floor(index / 2) + 1}`);
      lines.push('');
      lines.push(message.content);
    } else {
      lines.push('');
      lines.push(`### 🤖 回答 (${message.aiModel || 'AI'})`);
      if (message.processingTime) {
        lines.push(`*响应时间: ${(message.processingTime / 1000).toFixed(2)}秒*`);
      }
      lines.push('');
      lines.push(message.content);
    }
    lines.push('');
    lines.push('---');
    lines.push('');
  });
  
  // 页脚
  lines.push(`*Generated by LeiaoAI on ${new Date().toLocaleString('zh-CN')}*`);
  
  return lines.join('\n');
}

/**
 * 将Markdown内容转换为Blob，用于下载
 */
export function markdownToBlob(markdown: string): Blob {
  return new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
}

/**
 * 生成Markdown文件名（仅使用英文字母、数字、下划线和连字符）
 */
export function generateMarkdownFilename(session: ChatSession): string {
  const timestamp = session.createdAt.getTime();
  // 移除所有非ASCII字符，只保留字母、数字、下划线和连字符
  const cleanTitle = session.title
    .replace(/[^a-zA-Z0-9_-]/g, '_')
    .replace(/_+/g, '_')  // 将连续的下划线替换为单个
    .replace(/^_|_$/g, '') // 移除首尾的下划线
    .substring(0, 50)
    || 'chat'; // 如果标题为空，使用默认名称
  return `${timestamp}_${cleanTitle}.md`;
}

/**
 * 下载Markdown文件
 */
export function downloadMarkdown(session: ChatSession): void {
  const markdown = sessionToMarkdown(session);
  const blob = markdownToBlob(markdown);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = generateMarkdownFilename(session);
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

