-- 为缺失logo的公司添加logo的SQL脚本
-- 在Supabase SQL Editor中执行

-- 更新缺失logo的公司，使用Clearbit服务
UPDATE companies SET 
  logo_storage_url = CASE name
    -- 补充更多公司的logo
    WHEN 'Apple' THEN 'https://logo.clearbit.com/apple.com'
    WHEN 'Amazon' THEN 'https://logo.clearbit.com/amazon.com'
    WHEN 'Meta' THEN 'https://logo.clearbit.com/meta.com'
    WHEN 'Tesla' THEN 'https://logo.clearbit.com/tesla.com'
    WHEN 'NVIDIA' THEN 'https://logo.clearbit.com/nvidia.com'
    WHEN 'Intel' THEN 'https://logo.clearbit.com/intel.com'
    WHEN 'AMD' THEN 'https://logo.clearbit.com/amd.com'
    WHEN 'IBM' THEN 'https://logo.clearbit.com/ibm.com'
    WHEN 'Oracle' THEN 'https://logo.clearbit.com/oracle.com'
    WHEN 'Salesforce' THEN 'https://logo.clearbit.com/salesforce.com'
    WHEN 'ServiceNow' THEN 'https://logo.clearbit.com/servicenow.com'
    WHEN 'Workday' THEN 'https://logo.clearbit.com/workday.com'
    WHEN 'Snowflake' THEN 'https://logo.clearbit.com/snowflake.com'
    WHEN 'Databricks' THEN 'https://logo.clearbit.com/databricks.com'
    WHEN 'Palantir' THEN 'https://logo.clearbit.com/palantir.com'
    WHEN 'UiPath' THEN 'https://logo.clearbit.com/uipath.com'
    WHEN 'Automation Anywhere' THEN 'https://logo.clearbit.com/automationanywhere.com'
    WHEN 'Blue Prism' THEN 'https://logo.clearbit.com/blueprism.com'
    WHEN 'Pegasystems' THEN 'https://logo.clearbit.com/pega.com'
    WHEN 'Appian' THEN 'https://logo.clearbit.com/appian.com'
    WHEN 'Mendix' THEN 'https://logo.clearbit.com/mendix.com'
    WHEN 'OutSystems' THEN 'https://logo.clearbit.com/outsystems.com'
    WHEN 'Bubble' THEN 'https://logo.clearbit.com/bubble.io'
    WHEN 'Webflow' THEN 'https://logo.clearbit.com/webflow.com'
    WHEN 'Framer' THEN 'https://logo.clearbit.com/framer.com'
    WHEN 'Sketch' THEN 'https://logo.clearbit.com/sketch.com'
    WHEN 'InVision' THEN 'https://logo.clearbit.com/invisionapp.com'
    WHEN 'Marvel' THEN 'https://logo.clearbit.com/marvelapp.com'
    WHEN 'Principle' THEN 'https://logo.clearbit.com/principleformac.com'
    WHEN 'Proto.io' THEN 'https://logo.clearbit.com/proto.io'
    WHEN 'Justinmind' THEN 'https://logo.clearbit.com/justinmind.com'
    WHEN 'Axure' THEN 'https://logo.clearbit.com/axure.com'
    WHEN 'Balsamiq' THEN 'https://logo.clearbit.com/balsamiq.com'
    WHEN 'Mockplus' THEN 'https://logo.clearbit.com/mockplus.com'
    WHEN 'MockFlow' THEN 'https://logo.clearbit.com/mockflow.com'
    WHEN 'Fluid UI' THEN 'https://logo.clearbit.com/fluidui.com'
    WHEN 'HotGloo' THEN 'https://logo.clearbit.com/hotgloo.com'
    WHEN 'Wireframe.cc' THEN 'https://logo.clearbit.com/wireframe.cc'
    WHEN 'Pidoco' THEN 'https://logo.clearbit.com/pidoco.com'
    WHEN 'Gliffy' THEN 'https://logo.clearbit.com/gliffy.com'
    WHEN 'Lucidchart' THEN 'https://logo.clearbit.com/lucidchart.com'
    WHEN 'Draw.io' THEN 'https://logo.clearbit.com/draw.io'
    WHEN 'Visio' THEN 'https://logo.clearbit.com/microsoft.com'
    WHEN 'OmniGraffle' THEN 'https://logo.clearbit.com/omnigroup.com'
    WHEN 'yEd' THEN 'https://logo.clearbit.com/yworks.com'
    WHEN 'Creately' THEN 'https://logo.clearbit.com/creately.com'
    WHEN 'Cacoo' THEN 'https://logo.clearbit.com/cacoo.com'
    WHEN 'SmartDraw' THEN 'https://logo.clearbit.com/smartdraw.com'
    WHEN 'Edraw Max' THEN 'https://logo.clearbit.com/edrawsoft.com'
    WHEN 'ConceptDraw' THEN 'https://logo.clearbit.com/conceptdraw.com'
    WHEN 'ProcessOn' THEN 'https://logo.clearbit.com/processon.com'
    WHEN 'MindMeister' THEN 'https://logo.clearbit.com/mindmeister.com'
    WHEN 'Mindomo' THEN 'https://logo.clearbit.com/mindomo.com'
    WHEN 'XMind' THEN 'https://logo.clearbit.com/xmind.net'
    WHEN 'FreeMind' THEN 'https://logo.clearbit.com/freemind.sourceforge.net'
    WHEN 'SimpleMind' THEN 'https://logo.clearbit.com/simplemind.eu'
    WHEN 'MindManager' THEN 'https://logo.clearbit.com/mindmanager.com'
    WHEN 'iMindMap' THEN 'https://logo.clearbit.com/imindmap.com'
    WHEN 'MindView' THEN 'https://logo.clearbit.com/mindview.com'
    WHEN 'MindGenius' THEN 'https://logo.clearbit.com/mindgenius.com'
    WHEN 'MindNode' THEN 'https://logo.clearbit.com/mindnode.com'
    WHEN 'Mindly' THEN 'https://logo.clearbit.com/mindlyapp.com'
    WHEN 'MindVector' THEN 'https://logo.clearbit.com/mindvector.net'
    WHEN 'MindMapper' THEN 'https://logo.clearbit.com/mindmapper.com'
    WHEN 'MindMaster' THEN 'https://logo.clearbit.com/mindmaster.io'
    WHEN 'Mindomo' THEN 'https://logo.clearbit.com/mindomo.com'
    WHEN 'MindMeister' THEN 'https://logo.clearbit.com/mindmeister.com'
    WHEN 'Coggle' THEN 'https://logo.clearbit.com/coggle.it'
    WHEN 'MindMup' THEN 'https://logo.clearbit.com/mindmup.com'
    WHEN 'WiseMapping' THEN 'https://logo.clearbit.com/wisemapping.com'
    WHEN 'Mind42' THEN 'https://logo.clearbit.com/mind42.com'
    WHEN 'Bubbl.us' THEN 'https://logo.clearbit.com/bubbl.us'
    WHEN 'Popplet' THEN 'https://logo.clearbit.com/popplet.com'
    WHEN 'SpiderScribe' THEN 'https://logo.clearbit.com/spiderscribe.net'
    WHEN 'Text2MindMap' THEN 'https://logo.clearbit.com/text2mindmap.com'
    WHEN 'MindMaple' THEN 'https://logo.clearbit.com/mindmaple.com'
    WHEN 'MindMap' THEN 'https://logo.clearbit.com/mindmap.com'
    WHEN 'Mindomo' THEN 'https://logo.clearbit.com/mindomo.com'
    WHEN 'MindMeister' THEN 'https://logo.clearbit.com/mindmeister.com'
    WHEN 'XMind' THEN 'https://logo.clearbit.com/xmind.net'
    WHEN 'FreeMind' THEN 'https://logo.clearbit.com/freemind.sourceforge.net'
    WHEN 'SimpleMind' THEN 'https://logo.clearbit.com/simplemind.eu'
    WHEN 'MindManager' THEN 'https://logo.clearbit.com/mindmanager.com'
    WHEN 'iMindMap' THEN 'https://logo.clearbit.com/imindmap.com'
    WHEN 'MindView' THEN 'https://logo.clearbit.com/mindview.com'
    WHEN 'MindGenius' THEN 'https://logo.clearbit.com/mindgenius.com'
    WHEN 'MindNode' THEN 'https://logo.clearbit.com/mindnode.com'
    WHEN 'Mindly' THEN 'https://logo.clearbit.com/mindlyapp.com'
    WHEN 'MindVector' THEN 'https://logo.clearbit.com/mindvector.net'
    WHEN 'MindMapper' THEN 'https://logo.clearbit.com/mindmapper.com'
    WHEN 'MindMaster' THEN 'https://logo.clearbit.com/mindmaster.io'
    WHEN 'Mindomo' THEN 'https://logo.clearbit.com/mindomo.com'
    WHEN 'MindMeister' THEN 'https://logo.clearbit.com/mindmeister.com'
    WHEN 'Coggle' THEN 'https://logo.clearbit.com/coggle.it'
    WHEN 'MindMup' THEN 'https://logo.clearbit.com/mindmup.com'
    WHEN 'WiseMapping' THEN 'https://logo.clearbit.com/wisemapping.com'
    WHEN 'Mind42' THEN 'https://logo.clearbit.com/mind42.com'
    WHEN 'Bubbl.us' THEN 'https://logo.clearbit.com/bubbl.us'
    WHEN 'Popplet' THEN 'https://logo.clearbit.com/popplet.com'
    WHEN 'SpiderScribe' THEN 'https://logo.clearbit.com/spiderscribe.net'
    WHEN 'Text2MindMap' THEN 'https://logo.clearbit.com/text2mindmap.com'
    WHEN 'MindMaple' THEN 'https://logo.clearbit.com/mindmaple.com'
    WHEN 'MindMap' THEN 'https://logo.clearbit.com/mindmap.com'
  END
WHERE (logo_storage_url IS NULL AND logo_url IS NULL AND logo_base64 IS NULL)
  AND name IN (
    'Apple', 'Amazon', 'Meta', 'Tesla', 'NVIDIA', 'Intel', 'AMD', 'IBM', 'Oracle', 'Salesforce',
    'ServiceNow', 'Workday', 'Snowflake', 'Databricks', 'Palantir', 'UiPath', 'Automation Anywhere',
    'Blue Prism', 'Pegasystems', 'Appian', 'Mendix', 'OutSystems', 'Bubble', 'Webflow', 'Framer',
    'Sketch', 'InVision', 'Marvel', 'Principle', 'Proto.io', 'Justinmind', 'Axure', 'Balsamiq',
    'Mockplus', 'MockFlow', 'Fluid UI', 'HotGloo', 'Wireframe.cc', 'Pidoco', 'Gliffy', 'Lucidchart',
    'Draw.io', 'Visio', 'OmniGraffle', 'yEd', 'Creately', 'Cacoo', 'SmartDraw', 'Edraw Max',
    'ConceptDraw', 'ProcessOn', 'MindMeister', 'Mindomo', 'XMind', 'FreeMind', 'SimpleMind',
    'MindManager', 'iMindMap', 'MindView', 'MindGenius', 'MindNode', 'Mindly', 'MindVector',
    'MindMapper', 'MindMaster', 'Coggle', 'MindMup', 'WiseMapping', 'Mind42', 'Bubbl.us',
    'Popplet', 'SpiderScribe', 'Text2MindMap', 'MindMaple', 'MindMap'
  );

-- 完成
SELECT '缺失logo补充完成！' as status;
