-- 增强版AIverse数据插入脚本
-- 包含119家AIverse公司 + 179家补充公司
-- 在Supabase SQL Editor中执行

-- 1. 插入所有公司数据（包括补充的）
INSERT INTO companies (name, description) VALUES
('OpenAI', 'OpenAI是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Anthropic', 'Anthropic是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('xAI', 'xAI是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Google', 'Google是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('DeepSeek', 'DeepSeek是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Perplexity AI', 'Perplexity AI是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Microsoft', 'Microsoft是一家专注于Productivity领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Cursor', 'Cursor是一家专注于Developer Tools领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Synthesia', 'Synthesia是一家专注于Video领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Runway', 'Runway是一家专注于Video领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('OpusClip', 'OpusClip是一家专注于Video领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Luma AI', 'Luma AI是一家专注于Video领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('HeyGen', 'HeyGen是一家专注于Video领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('ByteDance', 'ByteDance是一家专注于Video领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Pictory', 'Pictory是一家专注于Video领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('InVideo', 'InVideo是一家专注于Video领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Descript', 'Descript是一家专注于Video领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Fliki', 'Fliki是一家专注于Video领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Steve', 'Steve是一家专注于Video领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Filmora', 'Filmora是一家专注于Video领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Midjourney', 'Midjourney是一家专注于Design领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Leonardo', 'Leonardo是一家专注于Design领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Canva', 'Canva是一家专注于Design领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Remove', 'Remove是一家专注于Design领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Firefly', 'Firefly是一家专注于Design领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Stability', 'Stability是一家专注于Design领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Openai', 'Openai是一家专注于Design领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Figma', 'Figma是一家专注于Design领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Krea', 'Krea是一家专注于Design领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Ideogram', 'Ideogram是一家专注于Design领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Adobe', 'Adobe是一家专注于Design领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Recraft', 'Recraft是一家专注于Design领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Elevenlabs', 'Elevenlabs是一家专注于Content Creation领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Murf', 'Murf是一家专注于Content Creation领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Suno', 'Suno是一家专注于Content Creation领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Udio', 'Udio是一家专注于Content Creation领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Speechify', 'Speechify是一家专注于Content Creation领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Play', 'Play是一家专注于Content Creation领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Resemble', 'Resemble是一家专注于Content Creation领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Aiva', 'Aiva是一家专注于Content Creation领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Soundraw', 'Soundraw是一家专注于Content Creation领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Krisp', 'Krisp是一家专注于Content Creation领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Grammarly', 'Grammarly是一家专注于Writing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Jasper', 'Jasper是一家专注于Writing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Copy', 'Copy是一家专注于Writing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Quillbot', 'Quillbot是一家专注于Writing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Rytr', 'Rytr是一家专注于Writing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Sudowrite', 'Sudowrite是一家专注于Writing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Writesonic', 'Writesonic是一家专注于Writing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Wordtune', 'Wordtune是一家专注于Writing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Lex', 'Lex是一家专注于Writing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Jenni', 'Jenni是一家专注于Writing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Prowritingaid', 'Prowritingaid是一家专注于Writing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Hypotenuse', 'Hypotenuse是一家专注于Writing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Github', 'Github是一家专注于Developer Tools领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Replit', 'Replit是一家专注于Developer Tools领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Tabnine', 'Tabnine是一家专注于Developer Tools领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Codeium', 'Codeium是一家专注于Developer Tools领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Lovable', 'Lovable是一家专注于Developer Tools领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('V0', 'V0是一家专注于Developer Tools领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Codewp', 'Codewp是一家专注于Developer Tools领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Huggingface', 'Huggingface是一家专注于Developer Tools领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Aistudio', 'Aistudio是一家专注于Developer Tools领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Groq', 'Groq是一家专注于Developer Tools领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Notion', 'Notion是一家专注于Productivity领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Zapier', 'Zapier是一家专注于Productivity领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('N8n', 'N8n是一家专注于Productivity领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Gamma', 'Gamma是一家专注于Productivity领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Fathom', 'Fathom是一家专注于Productivity领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Reclaim', 'Reclaim是一家专注于Productivity领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Otter', 'Otter是一家专注于Productivity领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Calendly', 'Calendly是一家专注于Productivity领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Taskade', 'Taskade是一家专注于Productivity领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Manus', 'Manus是一家专注于Productivity领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Monday', 'Monday是一家专注于Productivity领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Clickup', 'Clickup是一家专注于Productivity领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Adcreative', 'Adcreative是一家专注于Marketing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Hubspot', 'Hubspot是一家专注于Marketing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Persado', 'Persado是一家专注于Marketing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Phrasee', 'Phrasee是一家专注于Marketing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Patterns', 'Patterns是一家专注于Marketing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Theseventhsense', 'Theseventhsense是一家专注于Marketing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Brandwatch', 'Brandwatch是一家专注于Marketing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Albert', 'Albert是一家专注于Marketing领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Seamless', 'Seamless是一家专注于Sales领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Gong', 'Gong是一家专注于Sales领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Outreach', 'Outreach是一家专注于Sales领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Chorus', 'Chorus是一家专注于Sales领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Character', 'Character是一家专注于Chatbots领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Poe', 'Poe是一家专注于Chatbots领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Intercom', 'Intercom是一家专注于Customer Support领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Zendesk', 'Zendesk是一家专注于Customer Support领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Ada', 'Ada是一家专注于Customer Support领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Liveperson', 'Liveperson是一家专注于Customer Support领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Drift', 'Drift是一家专注于Customer Support领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Freshworks', 'Freshworks是一家专注于Customer Support领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Botpress', 'Botpress是一家专注于Chatbots领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Rasa', 'Rasa是一家专注于Chatbots领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Datarobot', 'Datarobot是一家专注于Analytics领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('H2o', 'H2o是一家专注于Analytics领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Tableau', 'Tableau是一家专注于Analytics领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Powerbi', 'Powerbi是一家专注于Analytics领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Qlik', 'Qlik是一家专注于Analytics领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Sisense', 'Sisense是一家专注于Analytics领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Thoughtspot', 'Thoughtspot是一家专注于Analytics领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Alteryx', 'Alteryx是一家专注于Analytics领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Khanacademy', 'Khanacademy是一家专注于Education领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Blog', 'Blog是一家专注于Education领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Coursera', 'Coursera是一家专注于Education领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Socratic', 'Socratic是一家专注于Education领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Quizlet', 'Quizlet是一家专注于Education领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Gradescope', 'Gradescope是一家专注于Education领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Carnegielearning', 'Carnegielearning是一家专注于Education领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Century', 'Century是一家专注于Education领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Deepai', 'Deepai是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Replika', 'Replika是一家专注于Chatbots领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Monkeylearn', 'Monkeylearn是一家专注于Analytics领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Lobe', 'Lobe是一家专注于Developer Tools领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Academy', 'Academy是一家专注于Education领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Apple', 'Apple是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Tesla', 'Tesla是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('NVIDIA', 'NVIDIA是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('IBM', 'IBM是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Intel', 'Intel是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('AMD', 'AMD是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Qualcomm', 'Qualcomm是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Salesforce', 'Salesforce是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Oracle', 'Oracle是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('SAP', 'SAP是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Autodesk', 'Autodesk是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Unity', 'Unity是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Epic Games', 'Epic Games是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Roblox', 'Roblox是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Snapchat', 'Snapchat是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('TikTok', 'TikTok是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Instagram', 'Instagram是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Twitter', 'Twitter是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('LinkedIn', 'LinkedIn是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Pinterest', 'Pinterest是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Reddit', 'Reddit是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Discord', 'Discord是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Slack', 'Slack是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Zoom', 'Zoom是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Teams', 'Teams是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Skype', 'Skype是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('WhatsApp', 'WhatsApp是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Telegram', 'Telegram是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Signal', 'Signal是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Element', 'Element是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Matrix', 'Matrix是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Mastodon', 'Mastodon是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Bluesky', 'Bluesky是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('GitHub', 'GitHub是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('GitLab', 'GitLab是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Bitbucket', 'Bitbucket是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Atlassian', 'Atlassian是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Airtable', 'Airtable是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Monday.com', 'Monday.com是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Asana', 'Asana是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Trello', 'Trello是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Jira', 'Jira是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Sketch', 'Sketch是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Adobe XD', 'Adobe XD是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('InVision', 'InVision是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Marvel', 'Marvel是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Principle', 'Principle是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Framer', 'Framer是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Webflow', 'Webflow是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Squarespace', 'Squarespace是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Wix', 'Wix是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Shopify', 'Shopify是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('WooCommerce', 'WooCommerce是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Magento', 'Magento是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('BigCommerce', 'BigCommerce是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Stripe', 'Stripe是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('PayPal', 'PayPal是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Square', 'Square是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Venmo', 'Venmo是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Cash App', 'Cash App是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Coinbase', 'Coinbase是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Binance', 'Binance是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Kraken', 'Kraken是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Gemini', 'Gemini是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('FTX', 'FTX是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Robinhood', 'Robinhood是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('E*TRADE', 'E*TRADE是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('TD Ameritrade', 'TD Ameritrade是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Charles Schwab', 'Charles Schwab是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Fidelity', 'Fidelity是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Vanguard', 'Vanguard是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('BlackRock', 'BlackRock是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Goldman Sachs', 'Goldman Sachs是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('JPMorgan Chase', 'JPMorgan Chase是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Bank of America', 'Bank of America是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Wells Fargo', 'Wells Fargo是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Citigroup', 'Citigroup是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Morgan Stanley', 'Morgan Stanley是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Deutsche Bank', 'Deutsche Bank是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('UBS', 'UBS是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Credit Suisse', 'Credit Suisse是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Barclays', 'Barclays是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('HSBC', 'HSBC是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('BNP Paribas', 'BNP Paribas是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Société Générale', 'Société Générale是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('ING', 'ING是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Rabobank', 'Rabobank是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Santander', 'Santander是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('BBVA', 'BBVA是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('UniCredit', 'UniCredit是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Intesa Sanpaolo', 'Intesa Sanpaolo是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Commerzbank', 'Commerzbank是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Lloyds Banking Group', 'Lloyds Banking Group是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Royal Bank of Scotland', 'Royal Bank of Scotland是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Standard Chartered', 'Standard Chartered是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('DBS', 'DBS是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('OCBC', 'OCBC是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('UOB', 'UOB是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('MUFG', 'MUFG是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Mizuho', 'Mizuho是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('SMBC', 'SMBC是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Nomura', 'Nomura是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('SoftBank', 'SoftBank是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Rakuten', 'Rakuten是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('LINE', 'LINE是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Kakao', 'Kakao是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Naver', 'Naver是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Samsung', 'Samsung是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('LG', 'LG是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Hyundai', 'Hyundai是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Kia', 'Kia是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('SK', 'SK是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('KT', 'KT是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('LG U+', 'LG U+是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('China Mobile', 'China Mobile是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('China Unicom', 'China Unicom是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('China Telecom', 'China Telecom是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Tencent', 'Tencent是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Alibaba', 'Alibaba是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Baidu', 'Baidu是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('JD.com', 'JD.com是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Meituan', 'Meituan是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Didi', 'Didi是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Xiaomi', 'Xiaomi是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Huawei', 'Huawei是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Oppo', 'Oppo是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Vivo', 'Vivo是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('OnePlus', 'OnePlus是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Realme', 'Realme是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Honor', 'Honor是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Lenovo', 'Lenovo是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Asus', 'Asus是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Acer', 'Acer是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('MSI', 'MSI是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Gigabyte', 'Gigabyte是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('EVGA', 'EVGA是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Corsair', 'Corsair是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Razer', 'Razer是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Logitech', 'Logitech是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('SteelSeries', 'SteelSeries是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('HyperX', 'HyperX是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Cooler Master', 'Cooler Master是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Thermaltake', 'Thermaltake是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Antec', 'Antec是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Fractal Design', 'Fractal Design是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('NZXT', 'NZXT是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Lian Li', 'Lian Li是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Phanteks', 'Phanteks是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('be quiet!', 'be quiet!是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Noctua', 'Noctua是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Arctic', 'Arctic是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Scythe', 'Scythe是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Deepcool', 'Deepcool是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('ID-Cooling', 'ID-Cooling是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Gamer Storm', 'Gamer Storm是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Enermax', 'Enermax是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Seasonic', 'Seasonic是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('FSP', 'FSP是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Silverstone', 'Silverstone是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Super Flower', 'Super Flower是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Rosewill', 'Rosewill是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('XFX', 'XFX是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Sapphire', 'Sapphire是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('PowerColor', 'PowerColor是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('ASRock', 'ASRock是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Biostar', 'Biostar是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('ECS', 'ECS是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Foxconn', 'Foxconn是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Pegatron', 'Pegatron是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Quanta', 'Quanta是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Wistron', 'Wistron是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Inventec', 'Inventec是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Compal', 'Compal是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Flextronics', 'Flextronics是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Jabil', 'Jabil是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Sanmina', 'Sanmina是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Celestica', 'Celestica是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Benchmark', 'Benchmark是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。'),
('Plexus', 'Plexus是一家专注于Artificial Intelligence领域的AI公司，致力于通过先进的人工智能技术为用户提供创新的解决方案。');

-- 2. 插入所有项目数据
WITH company_ids AS (
  SELECT name, id FROM companies WHERE name IN ('OpenAI', 'Anthropic', 'xAI', 'Google', 'DeepSeek', 'Perplexity AI', 'Microsoft', 'Cursor', 'Synthesia', 'Runway', 'OpusClip', 'Luma AI', 'HeyGen', 'ByteDance', 'Pictory', 'InVideo', 'Descript', 'Fliki', 'Steve', 'Filmora', 'Midjourney', 'Leonardo', 'Canva', 'Remove', 'Firefly', 'Stability', 'Openai', 'Figma', 'Krea', 'Ideogram', 'Adobe', 'Recraft', 'Elevenlabs', 'Murf', 'Suno', 'Udio', 'Speechify', 'Play', 'Resemble', 'Aiva', 'Soundraw', 'Krisp', 'Grammarly', 'Jasper', 'Copy', 'Quillbot', 'Rytr', 'Sudowrite', 'Writesonic', 'Wordtune', 'Lex', 'Jenni', 'Prowritingaid', 'Hypotenuse', 'Github', 'Replit', 'Tabnine', 'Codeium', 'Lovable', 'V0', 'Codewp', 'Huggingface', 'Aistudio', 'Groq', 'Notion', 'Zapier', 'N8n', 'Gamma', 'Fathom', 'Reclaim', 'Otter', 'Calendly', 'Taskade', 'Manus', 'Monday', 'Clickup', 'Adcreative', 'Hubspot', 'Persado', 'Phrasee', 'Patterns', 'Theseventhsense', 'Brandwatch', 'Albert', 'Seamless', 'Gong', 'Outreach', 'Chorus', 'Character', 'Poe', 'Intercom', 'Zendesk', 'Ada', 'Liveperson', 'Drift', 'Freshworks', 'Botpress', 'Rasa', 'Datarobot', 'H2o', 'Tableau', 'Powerbi', 'Qlik', 'Sisense', 'Thoughtspot', 'Alteryx', 'Khanacademy', 'Blog', 'Coursera', 'Socratic', 'Quizlet', 'Gradescope', 'Carnegielearning', 'Century', 'Deepai', 'Replika', 'Monkeylearn', 'Lobe', 'Academy', 'Apple', 'Tesla', 'NVIDIA', 'IBM', 'Intel', 'AMD', 'Qualcomm', 'Salesforce', 'Oracle', 'SAP', 'Autodesk', 'Unity', 'Epic Games', 'Roblox', 'Snapchat', 'TikTok', 'Instagram', 'Twitter', 'LinkedIn', 'Pinterest', 'Reddit', 'Discord', 'Slack', 'Zoom', 'Teams', 'Skype', 'WhatsApp', 'Telegram', 'Signal', 'Element', 'Matrix', 'Mastodon', 'Bluesky', 'GitHub', 'GitLab', 'Bitbucket', 'Atlassian', 'Airtable', 'Monday.com', 'Asana', 'Trello', 'Jira', 'Sketch', 'Adobe XD', 'InVision', 'Marvel', 'Principle', 'Framer', 'Webflow', 'Squarespace', 'Wix', 'Shopify', 'WooCommerce', 'Magento', 'BigCommerce', 'Stripe', 'PayPal', 'Square', 'Venmo', 'Cash App', 'Coinbase', 'Binance', 'Kraken', 'Gemini', 'FTX', 'Robinhood', 'E*TRADE', 'TD Ameritrade', 'Charles Schwab', 'Fidelity', 'Vanguard', 'BlackRock', 'Goldman Sachs', 'JPMorgan Chase', 'Bank of America', 'Wells Fargo', 'Citigroup', 'Morgan Stanley', 'Deutsche Bank', 'UBS', 'Credit Suisse', 'Barclays', 'HSBC', 'BNP Paribas', 'Société Générale', 'ING', 'Rabobank', 'Santander', 'BBVA', 'UniCredit', 'Intesa Sanpaolo', 'Commerzbank', 'Lloyds Banking Group', 'Royal Bank of Scotland', 'Standard Chartered', 'DBS', 'OCBC', 'UOB', 'MUFG', 'Mizuho', 'SMBC', 'Nomura', 'SoftBank', 'Rakuten', 'LINE', 'Kakao', 'Naver', 'Samsung', 'LG', 'Hyundai', 'Kia', 'SK', 'KT', 'LG U+', 'China Mobile', 'China Unicom', 'China Telecom', 'Tencent', 'Alibaba', 'Baidu', 'JD.com', 'Meituan', 'Didi', 'Xiaomi', 'Huawei', 'Oppo', 'Vivo', 'OnePlus', 'Realme', 'Honor', 'Lenovo', 'Asus', 'Acer', 'MSI', 'Gigabyte', 'EVGA', 'Corsair', 'Razer', 'Logitech', 'SteelSeries', 'HyperX', 'Cooler Master', 'Thermaltake', 'Antec', 'Fractal Design', 'NZXT', 'Lian Li', 'Phanteks', 'be quiet!', 'Noctua', 'Arctic', 'Scythe', 'Deepcool', 'ID-Cooling', 'Gamer Storm', 'Enermax', 'Seasonic', 'FSP', 'Silverstone', 'Super Flower', 'Rosewill', 'XFX', 'Sapphire', 'PowerColor', 'ASRock', 'Biostar', 'ECS', 'Foxconn', 'Pegatron', 'Quanta', 'Wistron', 'Inventec', 'Compal', 'Flextronics', 'Jabil', 'Sanmina', 'Celestica', 'Benchmark', 'Plexus')
)
INSERT INTO projects (company_id, name, description, category, website)
SELECT 
  ci.id,
  p.name,
  p.description,
  p.category,
  p.website
FROM company_ids ci
CROSS JOIN LATERAL (
  VALUES
    ('OpenAI', 'ChatGPT', 'Leading AI assistant for wide range of tasks, file analysis, summarization, and advanced reasoning with GPT-4o capabilities', 'Artificial Intelligence', 'https://chatgpt.com'),
    ('Anthropic', 'Claude', 'Advanced AI assistant by Anthropic optimized for coding, reliable code generation, collaborative communication, and long-form content analysis', 'Artificial Intelligence', 'https://claude.ai'),
    ('Anthropic', 'Anthropic Claude API', 'Enterprise API access to Claude AI with enhanced safety, constitutional AI training, and developer tools', 'Developer Tools', 'https://www.anthropic.com/api'),
    ('xAI', 'Grok', 'Uncensored AI assistant integrated with X (Twitter), featuring real-time information access and image generation capabilities', 'Artificial Intelligence', 'https://grok.x.ai'),
    ('Google', 'Gemini', 'Google''s multimodal AI with 2M token context window, audio overview feature, and advanced reasoning capabilities across text, image, and code', 'Artificial Intelligence', 'https://gemini.google.com'),
    ('Google', 'NotebookLM', 'Google''s AI note-taking with personal knowledge management and 57% growth in 2024, perfect for research and collaborative learning', 'Productivity', 'https://notebooklm.google.com'),
    ('DeepSeek', 'DeepSeek', 'Fastest growing AI tool with 88.6% popularity increase in 2024, offering advanced reasoning and coding capabilities with competitive performance', 'Artificial Intelligence', 'https://www.deepseek.com'),
    ('Perplexity AI', 'Perplexity AI', 'Conversational search engine with 37.7% growth in 2024, combining web search with AI reasoning for accurate, sourced answers', 'Artificial Intelligence', 'https://www.perplexity.ai'),
    ('Microsoft', 'Microsoft Copilot', 'AI-powered productivity tool and conversational chatbot integrated across Microsoft 365 suite with enterprise-grade security', 'Productivity', 'https://copilot.microsoft.com'),
    ('Cursor', 'Cursor', 'AI-powered IDE for writing code with 56% growth in 2024, featuring intelligent code completion, chat-based programming, and pair programming', 'Developer Tools', 'https://cursor.sh'),
    ('Synthesia', 'Synthesia', 'Professional AI video generator with photorealistic avatars for corporate training, marketing content, and multilingual videos', 'Video', 'https://www.synthesia.io'),
    ('Runway', 'Runway', 'Advanced AI video generation and editing platform with Gen-3 model for cinematic video creation and motion graphics', 'Video', 'https://runwayml.com'),
    ('OpusClip', 'OpusClip', 'AI-powered tool to break longer videos into engaging social media clips with automatic highlighting and viral score prediction', 'Video', 'https://www.opus.pro'),
    ('Luma AI', 'Luma AI', '3D model generation and video creation platform with Dream Machine for realistic video synthesis from text prompts', 'Video', 'https://lumalabs.ai'),
    ('HeyGen', 'HeyGen', 'AI avatar video generation platform for creating spokesperson videos with multilingual support and emotion control', 'Video', 'https://www.heygen.com'),
    ('ByteDance', 'CapCut', 'AI video editing platform with automated editing features, background removal, and social media optimization', 'Video', 'https://www.capcut.com'),
    ('Pictory', 'Pictory', 'AI video creation platform that transforms text articles and blog posts into engaging video content with voiceovers', 'Video', 'https://pictory.ai'),
    ('InVideo', 'InVideo', 'Comprehensive AI video generator with 5000+ templates and automated video creation workflows for marketing', 'Video', 'https://invideo.io'),
    ('Descript', 'Descript', 'All-in-one AI video editor with transcription, overdub voice cloning, and collaborative editing features', 'Video', 'https://www.descript.com'),
    ('Fliki', 'Fliki', 'AI video creation platform that converts text to video with realistic AI voices in multiple languages', 'Video', 'https://fliki.ai'),
    ('Steve', 'Steve AI', 'AI video maker that creates animated and live-action videos from text scripts with customizable characters', 'Video', 'https://www.steve.ai'),
    ('Filmora', 'Wondershare Filmora', 'AI-powered video editing software with automatic scene detection, smart cutout, and AI music generation', 'Video', 'https://filmora.wondershare.com'),
    ('Midjourney', 'Midjourney', 'Leading AI image generation platform with painterly aesthetic, advanced prompt engineering, and community-driven improvements', 'Design', 'https://www.midjourney.com'),
    ('Leonardo', 'Leonardo', 'Advanced AI image generation platform with fine-tuned models for different artistic styles and commercial use rights', 'Design', 'https://leonardo.ai'),
    ('Canva', 'Canva Magic Studio', 'AI-powered design suite with automated design generation, background removal, and smart editing features', 'Design', 'https://www.canva.com/magic-studio'),
    ('Remove', 'Remove.bg', 'AI background removal tool with instant processing for professional photo editing and batch processing', 'Design', 'https://www.remove.bg'),
    ('Firefly', 'Adobe Firefly', 'Adobe''s AI image generation and editing suite integrated into Creative Cloud with commercial safety guarantees', 'Design', 'https://firefly.adobe.com'),
    ('Stability', 'Stable Diffusion', 'Open-source AI image generation model with community-driven improvements, ControlNet support, and unlimited customizations', 'Design', 'https://stability.ai/stable-diffusion'),
    ('Openai', 'DALL-E 3', 'OpenAI''s latest image generation model integrated with ChatGPT, offering photorealistic and artistic image creation', 'Design', 'https://openai.com/dall-e-3'),
    ('Figma', 'Figma AI', 'AI-powered design assistance integrated into Figma with automated layout suggestions and design system generation', 'Design', 'https://www.figma.com/ai'),
    ('Krea', 'Krea AI', 'Real-time AI image generation platform with live canvas editing and instant visual feedback', 'Design', 'https://www.krea.ai'),
    ('Ideogram', 'Ideogram', 'AI image generator specializing in text rendering within images and graphic design elements', 'Design', 'https://ideogram.ai'),
    ('Adobe', 'Adobe Express', 'AI-powered design platform with quick actions, template customization, and social media optimization', 'Design', 'https://www.adobe.com/express'),
    ('Recraft', 'Recraft', 'AI design tool for creating brand-consistent graphics, illustrations, and marketing materials with style control', 'Design', 'https://www.recraft.ai'),
    ('Elevenlabs', 'ElevenLabs', 'Leading AI voice generation and cloning platform with realistic speech synthesis and emotion control for content creation', 'Content Creation', 'https://elevenlabs.io'),
    ('Murf', 'Murf.ai', 'Professional AI voice generation platform with clean interface, diverse voice options, and commercial licensing', 'Content Creation', 'https://murf.ai'),
    ('Suno', 'Suno', 'AI music generator for creating background music, soundtracks, and complete songs with text prompts and style control', 'Content Creation', 'https://www.suno.ai'),
    ('Udio', 'Udio', 'AI music generator designed for musicians with advanced composition, arrangement features, and professional audio quality', 'Content Creation', 'https://www.udio.com'),
    ('Speechify', 'Speechify', 'AI text-to-speech platform with natural voices, speed control, and integration across devices for accessibility', 'Content Creation', 'https://speechify.com'),
    ('Speechify', 'Speechify Education', 'AI text-to-speech platform designed for students with learning differences and accessibility needs', 'Education', 'https://speechify.com/education'),
    ('Play', 'Play.ht', 'AI voice generator with ultra-realistic voices, emotion control, and API access for developers and content creators', 'Content Creation', 'https://play.ht'),
    ('Play', 'AI Dungeon', 'AI-powered text adventure game with infinite storylines and creative writing assistance capabilities', 'Content Creation', 'https://play.aidungeon.io'),
    ('Resemble', 'Resemble AI', 'AI voice cloning platform with real-time voice conversion and custom voice model training capabilities', 'Content Creation', 'https://www.resemble.ai'),
    ('Aiva', 'AIVA', 'AI music composition platform for creating original soundtracks, theme music, and background scores for media', 'Content Creation', 'https://www.aiva.ai'),
    ('Soundraw', 'Soundraw', 'AI music generator for content creators with royalty-free music creation and customizable track elements', 'Content Creation', 'https://soundraw.io'),
    ('Krisp', 'Krisp', 'AI-powered noise cancellation and voice enhancement tool for professional meetings and content recording', 'Content Creation', 'https://krisp.ai'),
    ('Grammarly', 'Grammarly', 'Advanced AI writing assistant and grammar checker with tone detection, style suggestions, and plagiarism detection', 'Writing', 'https://www.grammarly.com'),
    ('Grammarly', 'Grammarly for Students', 'AI writing assistant specifically designed for academic writing with citation support and plagiarism detection', 'Education', 'https://www.grammarly.com/edu'),
    ('Jasper', 'Jasper.ai', 'Comprehensive AI marketing content creation platform for campaigns, blog posts, and brand messaging with brand voice training', 'Writing', 'https://www.jasper.ai'),
    ('Copy', 'Copy.ai', 'AI copywriting tool for marketing content, social media posts, email campaigns, and business communications', 'Writing', 'https://www.copy.ai'),
    ('Quillbot', 'QuillBot', 'AI writing enhancement and paraphrasing tool for improving content quality, clarity, and avoiding plagiarism', 'Writing', 'https://quillbot.com'),
    ('Rytr', 'Rytr', 'AI writing assistant optimized for short-form content creation, copywriting, and social media posts with tone control', 'Writing', 'https://rytr.me'),
    ('Sudowrite', 'Sudowrite', 'Creative writing assistant specifically designed for fiction writers, novelists, and storytellers with plot development', 'Writing', 'https://www.sudowrite.com'),
    ('Writesonic', 'Writesonic', 'AI content creation platform for articles, ads, emails, and website copy with SEO optimization features', 'Writing', 'https://writesonic.com'),
    ('Wordtune', 'Wordtune', 'AI writing companion that helps rewrite and improve sentences for clarity, tone, and impact in real-time', 'Writing', 'https://www.wordtune.com'),
    ('Lex', 'Lex', 'AI-powered writing tool designed for long-form content with collaborative features and intelligent suggestions', 'Writing', 'https://lex.page'),
    ('Jenni', 'Jenni AI', 'AI writing assistant for academic and research writing with citation management and plagiarism checking', 'Writing', 'https://jenni.ai'),
    ('Prowritingaid', 'ProWritingAid', 'AI-powered writing editor with in-depth analysis, style improvement suggestions, and comprehensive writing reports', 'Writing', 'https://prowritingaid.com'),
    ('Hypotenuse', 'Hypotenuse AI', 'AI content generator for e-commerce, marketing copy, and product descriptions with bulk content creation', 'Writing', 'https://www.hypotenuse.ai'),
    ('Github', 'GitHub Copilot', 'AI pair programming assistant integrated into development environments for intelligent code completion and generation', 'Developer Tools', 'https://github.com/features/copilot'),
    ('Github', 'CodeT5', 'AI code generation and understanding model for multiple programming languages with code summarization', 'Developer Tools', 'https://github.com/salesforce/CodeT5'),
    ('Replit', 'Replit', 'AI-powered coding environment with collaborative development, instant deployment, and intelligent code assistance', 'Developer Tools', 'https://replit.com'),
    ('Tabnine', 'Tabnine', 'AI code completion platform that works across IDEs with context-aware suggestions and team learning', 'Developer Tools', 'https://www.tabnine.com'),
    ('Codeium', 'Codeium', 'Free AI code completion tool with support for 70+ programming languages and IDE integrations', 'Developer Tools', 'https://codeium.com'),
    ('Lovable', 'Lovable', 'Build complete software applications by prompting with natural language descriptions and visual requirements', 'Developer Tools', 'https://lovable.dev'),
    ('V0', 'v0 by Vercel', 'AI-powered web development tool that generates React components and complete applications from prompts', 'Developer Tools', 'https://v0.dev'),
    ('Codewp', 'CodeWP', 'AI code generator specifically for WordPress development with plugin creation and theme customization', 'Developer Tools', 'https://codewp.ai'),
    ('Huggingface', 'Hugging Face', 'Leading AI model platform and community for sharing, training, and deploying machine learning models and datasets', 'Developer Tools', 'https://huggingface.co'),
    ('Aistudio', 'Google AI Studio', 'AI development platform with 80% growth for building and prototyping with Google''s Gemini and PaLM models', 'Developer Tools', 'https://aistudio.google.com'),
    ('Groq', 'Groq', 'High-speed AI inference platform optimized for real-time AI applications with ultra-low latency responses', 'Developer Tools', 'https://groq.com'),
    ('Notion', 'Notion AI', 'AI-enhanced knowledge management and productivity suite with intelligent content creation and database automation', 'Productivity', 'https://www.notion.so/product/ai'),
    ('Zapier', 'Zapier', 'Automation platform with AI features for connecting 5000+ apps and automating complex business workflows', 'Productivity', 'https://zapier.com'),
    ('N8n', 'n8n', 'Visual workflow automation tool with AI integrations, self-hosted options, and advanced business process automation', 'Productivity', 'https://n8n.io'),
    ('Gamma', 'Gamma', 'AI presentation builder that creates beautiful slides, documents, and websites from text prompts and outlines', 'Productivity', 'https://gamma.app'),
    ('Fathom', 'Fathom', 'AI meeting notetaker that automatically records, transcribes, summarizes, and creates action items from meetings', 'Productivity', 'https://fathom.video'),
    ('Reclaim', 'Reclaim', 'AI scheduling assistant that optimizes calendar management, time blocking, and work-life balance automatically', 'Productivity', 'https://reclaim.ai'),
    ('Otter', 'Otter.ai', 'AI meeting transcription and note-taking platform with real-time collaboration and automated summaries', 'Productivity', 'https://otter.ai'),
    ('Calendly', 'Calendly AI', 'AI-powered scheduling platform with smart meeting optimization and automated follow-up management', 'Productivity', 'https://calendly.com'),
    ('Taskade', 'Taskade', 'AI-powered productivity platform combining task management, mind mapping, and collaborative workspaces with AI automation', 'Productivity', 'https://www.taskade.com'),
    ('Manus', 'Manus', 'AI agent platform for automating various business tasks, workflows, and repetitive processes across teams', 'Productivity', 'https://www.manus.ai'),
    ('Monday', 'Monday.com AI', 'AI-enhanced project management platform with automated workflows, predictive analytics, and smart task assignment', 'Productivity', 'https://monday.com'),
    ('Clickup', 'Clickup AI', 'AI-powered project management with automated task creation, smart scheduling, and intelligent progress tracking', 'Productivity', 'https://clickup.com/ai'),
    ('Adcreative', 'AdCreative', 'AI-powered ad creative generation platform for performance marketing campaigns with conversion optimization', 'Marketing', 'https://www.adcreative.ai'),
    ('Hubspot', 'HubSpot AI', 'AI-enhanced CRM and marketing automation platform with lead scoring, content generation, and sales insights', 'Marketing', 'https://www.hubspot.com/artificial-intelligence'),
    ('Persado', 'Persado', 'AI-powered marketing language optimization platform that generates high-converting marketing copy and messaging', 'Marketing', 'https://www.persado.com'),
    ('Phrasee', 'Phrasee', 'AI copywriting platform specialized in email subject lines, social media posts, and marketing copy optimization', 'Marketing', 'https://phrasee.co'),
    ('Patterns', 'Patterns', 'AI-powered ecommerce marketing platform with automated product recommendations and personalization', 'Marketing', 'https://patterns.app'),
    ('Theseventhsense', 'Seventh Sense', 'AI email delivery optimization platform that uses machine learning to improve open rates and engagement', 'Marketing', 'https://www.theseventhsense.com'),
    ('Brandwatch', 'Brandwatch', 'AI-powered social media monitoring and consumer intelligence platform with sentiment analysis and trend detection', 'Marketing', 'https://www.brandwatch.com'),
    ('Albert', 'Albert AI', 'Autonomous AI marketing platform that manages and optimizes digital advertising campaigns across channels', 'Marketing', 'https://albert.ai'),
    ('Seamless', 'Seamless.AI', 'AI-powered sales prospecting platform for finding verified contact information and building targeted lead lists', 'Sales', 'https://seamless.ai'),
    ('Gong', 'Gong', 'AI revenue intelligence platform that analyzes sales conversations to improve deal outcomes and team performance', 'Sales', 'https://www.gong.io'),
    ('Outreach', 'Outreach', 'AI-powered sales engagement platform with automated sequences, conversation intelligence, and pipeline management', 'Sales', 'https://www.outreach.io'),
    ('Chorus', 'Chorus', 'AI conversation analytics platform for sales teams with call recording, coaching insights, and deal risk analysis', 'Sales', 'https://www.chorus.ai'),
    ('Character', 'Character.ai', 'AI character chatbot platform for creating and conversing with custom AI personalities for entertainment and education', 'Chatbots', 'https://character.ai'),
    ('Poe', 'Poe', 'AI chatbot aggregator by Quora providing access to multiple AI models including Claude, GPT, and others in one platform', 'Chatbots', 'https://poe.com'),
    ('Intercom', 'Intercom Fin', 'AI-powered customer service chatbot with natural language understanding and seamless handoff to human agents', 'Customer Support', 'https://www.intercom.com/fin'),
    ('Zendesk', 'Zendesk AI', 'AI-enhanced customer support platform with automated ticket routing, sentiment analysis, and response suggestions', 'Customer Support', 'https://www.zendesk.com/ai'),
    ('Ada', 'Ada', 'AI chatbot platform for customer service with no-code bot building and automated resolution of common inquiries', 'Customer Support', 'https://www.ada.cx'),
    ('Liveperson', 'LivePerson', 'Conversational AI platform for customer engagement with voice and text capabilities across multiple channels', 'Customer Support', 'https://www.liveperson.com'),
    ('Drift', 'Drift', 'AI-powered conversational marketing platform with chatbots for lead qualification and customer engagement', 'Customer Support', 'https://www.drift.com'),
    ('Freshworks', 'Freshworks Freddy AI', 'AI assistant integrated across Freshworks suite for customer service, sales, and marketing automation', 'Customer Support', 'https://www.freshworks.com/freddy-ai'),
    ('Botpress', 'Botpress', 'Open-source chatbot development platform with AI capabilities and enterprise-grade deployment options', 'Chatbots', 'https://botpress.com'),
    ('Rasa', 'Rasa', 'Open-source framework for building AI assistants and chatbots with advanced natural language understanding', 'Chatbots', 'https://rasa.com'),
    ('Datarobot', 'DataRobot', 'Enterprise AI platform for automated machine learning, predictive analytics, and business intelligence insights', 'Analytics', 'https://www.datarobot.com'),
    ('H2o', 'H2O.ai', 'Open-source machine learning platform with automated ML capabilities and enterprise AI deployment solutions', 'Analytics', 'https://www.h2o.ai'),
    ('Tableau', 'Tableau AI', 'AI-powered data visualization and business intelligence platform with automated insights and natural language queries', 'Analytics', 'https://www.tableau.com'),
    ('Powerbi', 'Microsoft Power BI AI', 'Business intelligence platform with AI-driven insights, automated data preparation, and natural language Q&A', 'Analytics', 'https://powerbi.microsoft.com'),
    ('Qlik', 'Qlik Sense AI', 'Self-service analytics platform with AI-powered insights, automated data discovery, and augmented analytics', 'Analytics', 'https://www.qlik.com/us/products/qlik-sense'),
    ('Sisense', 'Sisense AI', 'AI-driven analytics platform that simplifies complex data analysis with automated insights and ML capabilities', 'Analytics', 'https://www.sisense.com'),
    ('Thoughtspot', 'ThoughtSpot', 'Search-driven analytics platform with AI-powered insights and natural language data queries for business users', 'Analytics', 'https://www.thoughtspot.com'),
    ('Alteryx', 'Alteryx', 'Self-service data analytics platform with automated machine learning and predictive analytics capabilities', 'Analytics', 'https://www.alteryx.com'),
    ('Khanacademy', 'Khan Academy Khanmigo', 'AI tutoring assistant that provides personalized learning support and guided practice across subjects', 'Education', 'https://www.khanacademy.org/khan-labs'),
    ('Blog', 'Duolingo Max', 'AI-powered language learning with personalized lessons, conversation practice, and adaptive learning paths', 'Education', 'https://blog.duolingo.com/duolingo-max'),
    ('Coursera', 'Coursera AI', 'AI-enhanced online learning platform with personalized course recommendations and adaptive assessment', 'Education', 'https://www.coursera.org'),
    ('Socratic', 'Socratic by Google', 'AI homework helper that provides step-by-step explanations and learning resources across subjects', 'Education', 'https://socratic.org'),
    ('Quizlet', 'Quizlet AI', 'AI-enhanced study platform with intelligent flashcards, personalized learning modes, and adaptive testing', 'Education', 'https://quizlet.com'),
    ('Gradescope', 'Gradescope AI', 'AI-assisted grading platform for educators with automated feedback and rubric-based assessment', 'Education', 'https://www.gradescope.com'),
    ('Carnegielearning', 'Carnegie Learning', 'AI-powered adaptive learning platform for mathematics with personalized instruction and real-time feedback', 'Education', 'https://www.carnegielearning.com'),
    ('Century', 'Century Tech', 'AI platform for personalized learning with adaptive content delivery and progress tracking for educators', 'Education', 'https://www.century.tech'),
    ('Deepai', 'DeepAI', 'Comprehensive collection of AI tools for image generation, text processing, and analysis with API access', 'Artificial Intelligence', 'https://deepai.org'),
    ('Replika', 'Replika', 'AI companion app for emotional support and conversation with personalized AI personality development', 'Chatbots', 'https://replika.ai'),
    ('Monkeylearn', 'MonkeyLearn', 'No-code text analysis platform with sentiment analysis, keyword extraction, and custom AI model training', 'Analytics', 'https://monkeylearn.com'),
    ('Lobe', 'Lobe', 'Microsoft''s visual machine learning tool for creating custom AI models without coding experience required', 'Developer Tools', 'https://www.lobe.ai'),
    ('Academy', 'Runway Academy', 'Educational platform for learning AI tools and creative applications with hands-on tutorials and projects', 'Education', 'https://academy.runwayml.com')
) AS p(company_name, name, description, category, website)
WHERE ci.name = p.company_name;

-- 完成
SELECT '增强版AIverse数据插入完成！共298家公司' as status;