-- Migration: create_sample_stories
-- Created at: 1759901392

-- Create 18 sample stories with LeiaoAI Agent as author

-- English stories
INSERT INTO stories (
  author_id, title, content, excerpt, cover_image_url, status, category, 
  read_time_minutes, language, views_count, likes_count, saves_count, 
  comments_count, published_at, created_at, updated_at
) VALUES 
(
  'aaaaaaaa-1111-2222-3333-444444444444',
  'AI Revolutionizing Healthcare: From Diagnosis to Treatment',
  'Artificial Intelligence is transforming healthcare delivery across every medical specialty. From radiology AI that can detect cancers earlier than human specialists to drug discovery platforms that accelerate pharmaceutical research, AI applications in medicine are saving lives and reducing costs. Machine learning algorithms now assist surgeons in complex procedures, predict patient deterioration in ICUs, and provide personalized treatment recommendations based on genetic profiles. The integration of AI with electronic health records enables physicians to make more informed decisions while natural language processing helps extract insights from clinical notes. Telemedicine platforms powered by AI can perform preliminary diagnoses and triage patients effectively. As we advance into 2025, the convergence of AI, genomics, and precision medicine promises to deliver truly personalized healthcare experiences that were unimaginable just a decade ago.',
  'Exploring how AI is revolutionizing healthcare from diagnosis to personalized treatment delivery.',
  '/story-images/healthcare-ai-1.png',
  'published',
  'AI Applications',
  6,
  'en',
  45230,
  342,
  87,
  23,
  NOW(),
  NOW(),
  NOW()
),
(
  'aaaaaaaa-1111-2222-3333-444444444444',
  'The Future of Finance: AI-Powered Investment Strategies',
  'The financial industry is experiencing a paradigm shift as artificial intelligence reshapes investment strategies and risk management practices. Algorithmic trading systems now execute millions of transactions per second, identifying market inefficiencies that human traders would miss. Robo-advisors democratize wealth management by providing sophisticated portfolio optimization to retail investors. Credit scoring models leverage alternative data sources including social media behavior and transaction patterns to assess creditworthiness more accurately. AI-powered fraud detection systems protect consumers by identifying suspicious activities in real-time. Hedge funds employ machine learning to analyze satellite imagery, social sentiment, and macroeconomic indicators for alpha generation. Regulatory technology (RegTech) solutions automate compliance monitoring and reporting. As we move forward, quantum computing integration with AI will unlock even more powerful financial modeling capabilities, while blockchain technology ensures transparency and security in AI-driven financial services.',
  'How AI is transforming finance through algorithmic trading and intelligent risk management.',
  '/story-images/finance-ai-1.png',
  'published',
  'Finance AI',
  7,
  'en',
  38920,
  289,
  76,
  19,
  NOW(),
  NOW(),
  NOW()
),
(
  'aaaaaaaa-1111-2222-3333-444444444444',
  'Building Scalable Startups: Lessons from Silicon Valley',
  'Creating a scalable startup requires more than just a great idea—it demands strategic thinking, execution excellence, and the ability to adapt quickly to market feedback. Successful Silicon Valley entrepreneurs understand that product-market fit is the foundation of any scalable business. This involves iterating rapidly based on user feedback, measuring key metrics religiously, and being willing to pivot when necessary. Building the right team is equally crucial; startups need versatile individuals who can wear multiple hats and grow with the company. Technology infrastructure must be designed for scale from day one, utilizing cloud services and modern development practices. Fundraising strategy should align with growth milestones, securing enough runway while maintaining focus on execution. Customer acquisition requires systematic experimentation with different channels and optimization of the entire sales funnel. Legal and compliance frameworks must be established early to avoid costly mistakes later. The most successful startups develop unique company cultures that attract top talent and foster innovation throughout their growth journey.',
  'Essential strategies for building scalable startups based on Silicon Valley best practices.',
  '/story-images/startup-ai-1.png',
  'published',
  'Startup Interview',
  8,
  'en',
  52140,
  398,
  102,
  31,
  NOW(),
  NOW(),
  NOW()
),
(
  'aaaaaaaa-1111-2222-3333-444444444444',
  'The Art of AI-Powered Content Creation',
  'Content creation is being revolutionized by artificial intelligence tools that augment human creativity rather than replace it. Modern AI writing assistants help authors overcome writer''s block, generate ideas, and refine their prose while maintaining their unique voice. Video content creators leverage AI for automated editing, color correction, and even generating synthetic media for demonstrations. Social media managers use AI to optimize posting schedules, create engaging captions, and analyze audience sentiment. Graphic designers collaborate with AI tools to generate initial concepts, create variations, and automate repetitive tasks. Podcasters employ AI for transcription, show notes generation, and audio enhancement. The key to successful AI-powered content creation lies in understanding these tools as collaborators rather than replacements. Human creativity, emotional intelligence, and cultural context remain irreplaceable. The most effective content creators combine AI efficiency with human insight to produce authentic, engaging, and valuable content that resonates with their audiences at scale.',
  'Exploring how AI tools are enhancing content creation while preserving human creativity.',
  '/story-images/content-ai-1.png',
  'published',
  'AI Applications',
  5,
  'en',
  31780,
  245,
  63,
  16,
  NOW(),
  NOW(),
  NOW()
),
(
  'aaaaaaaa-1111-2222-3333-444444444444',
  'E-commerce Evolution: AI-Driven Shopping Experiences',
  'E-commerce platforms are leveraging artificial intelligence to create personalized shopping experiences that drive customer satisfaction and business growth. Recommendation engines analyze customer behavior, purchase history, and browsing patterns to suggest relevant products with unprecedented accuracy. Visual search technology allows customers to find products using images rather than keywords, revolutionizing product discovery. Chatbots powered by natural language processing provide 24/7 customer support, handling inquiries, processing returns, and upselling relevant items. Dynamic pricing algorithms optimize prices in real-time based on demand, inventory levels, and competitor analysis. Supply chain optimization uses AI to predict demand, manage inventory, and reduce shipping costs. Fraud detection systems protect both merchants and customers by identifying suspicious transactions instantly. Virtual try-on experiences using augmented reality reduce return rates for fashion and furniture retailers. As voice commerce and social commerce gain traction, AI continues to evolve the shopping experience across all touchpoints.',
  'How AI is transforming e-commerce through personalization and intelligent automation.',
  '/story-images/ecommerce-ai-1.png',
  'published',
  'AI Applications',
  6,
  'en',
  41560,
  312,
  79,
  22,
  NOW(),
  NOW(),
  NOW()
),
(
  'aaaaaaaa-1111-2222-3333-444444444444',
  'Education Revolution: AI Tutoring and Personalized Learning',
  'Educational technology powered by artificial intelligence is personalizing learning experiences and making quality education more accessible worldwide. Adaptive learning platforms adjust difficulty levels and teaching methods based on individual student progress and learning styles. AI tutoring systems provide one-on-one support, explaining concepts in multiple ways until students achieve mastery. Automated grading systems free teachers to focus on instruction rather than administrative tasks while providing detailed feedback to students. Language learning apps use speech recognition and natural language processing to improve pronunciation and conversation skills. Educational analytics help institutions identify at-risk students early and provide targeted interventions. Virtual reality combined with AI creates immersive learning environments for subjects like history, science, and medicine. Accessibility tools powered by AI help students with disabilities participate fully in educational activities. As AI continues to evolve, we''re moving toward truly personalized education systems that adapt to each learner''s unique needs, pace, and interests.',
  'Discovering how AI is revolutionizing education through personalized learning and intelligent tutoring.',
  '/story-images/education-ai-1.png',
  'published',
  'AI Applications',
  7,
  'en',
  47890,
  365,
  94,
  28,
  NOW(),
  NOW(),
  NOW()
),
(
  'aaaaaaaa-1111-2222-3333-444444444444',
  'Manufacturing 4.0: AI-Powered Smart Factories',
  'The manufacturing industry is undergoing a digital transformation through Industry 4.0 initiatives that integrate artificial intelligence with traditional production processes. Predictive maintenance systems analyze sensor data to predict equipment failures before they occur, reducing downtime and maintenance costs. Quality control systems use computer vision to detect defects with greater accuracy than human inspectors. Production optimization algorithms balance efficiency, quality, and resource utilization in real-time. Supply chain management leverages AI to forecast demand, optimize inventory levels, and coordinate with suppliers. Robotics and automation continue to evolve with AI, enabling more flexible and adaptable manufacturing systems. Digital twins create virtual replicas of production lines for simulation and optimization. Energy management systems optimize consumption patterns to reduce costs and environmental impact. Worker safety is enhanced through AI-powered monitoring systems that detect hazardous conditions and ensure compliance with safety protocols. The result is smart factories that are more efficient, sustainable, and responsive to market demands.',
  'Exploring how AI is transforming manufacturing through smart factories and predictive systems.',
  '/story-images/manufacturing-ai-1.png',
  'published',
  'AI Applications',
  8,
  'en',
  35670,
  267,
  68,
  18,
  NOW(),
  NOW(),
  NOW()
),
(
  'aaaaaaaa-1111-2222-3333-444444444444',
  'Real Estate Innovation: AI in Property Management and Investment',
  'The real estate industry is embracing artificial intelligence to streamline operations, enhance investment decisions, and improve customer experiences. Property valuation models use machine learning to analyze market data, property features, and neighborhood trends for accurate pricing. Virtual property tours powered by AI and augmented reality allow buyers to explore homes remotely. Predictive analytics help investors identify emerging markets and profitable opportunities before they become obvious to competitors. Property management systems automate tenant screening, lease administration, and maintenance scheduling. Smart building technologies optimize energy usage, security, and tenant comfort through AI-driven controls. Market analysis tools process vast amounts of data to identify trends and forecast property values. Customer relationship management systems personalize communications and automate follow-ups with potential buyers and tenants. Construction project management leverages AI for scheduling, resource allocation, and risk assessment. As the industry continues to digitize, AI will play an increasingly important role in making real estate transactions more efficient and transparent.',
  'How AI is revolutionizing real estate through smart property management and investment analytics.',
  '/story-images/realestate-ai-1.png',
  'published',
  'AI Applications',
  6,
  'en',
  28340,
  218,
  55,
  15,
  NOW(),
  NOW(),
  NOW()
),
(
  'aaaaaaaa-1111-2222-3333-444444444444',
  'The Developer''s Guide to AI-Assisted Programming',
  'Software development is being transformed by artificial intelligence tools that enhance productivity, code quality, and developer experience. AI-powered code completion systems like GitHub Copilot generate entire functions based on comments or partial implementations. Automated testing frameworks create comprehensive test suites and identify edge cases that developers might miss. Code review tools analyze pull requests for potential bugs, security vulnerabilities, and style inconsistencies. Debugging assistants help developers understand complex codebases and suggest fixes for common issues. Documentation generators create API docs and code comments automatically from source code analysis. Performance optimization tools identify bottlenecks and suggest improvements for better application performance. Natural language interfaces allow developers to describe functionality in plain English and receive working code implementations. DevOps automation uses AI to optimize deployment pipelines, predict system failures, and manage infrastructure resources. The key to leveraging these tools effectively is understanding their capabilities and limitations while maintaining coding fundamentals and problem-solving skills.',
  'A comprehensive guide to AI tools that are transforming software development and programming.',
  '/story-images/coding-ai-1.png',
  'published',
  'AI Applications',
  7,
  'en',
  44250,
  334,
  85,
  26,
  NOW(),
  NOW(),
  NOW()
);;